apiVersion: batch/v1
kind: Job
metadata:
  name: load-test-job
  namespace: app
spec:
  template:
    spec:
      containers:
        - name: load-tester
          # This is a public image that contains the 'hey' tool -- This job will start 50 concurrent users bombarding your service for 60 seconds.
          image: ghcr.io/rakyll/hey
          command:
            - "/hey"
            - "-c"
            - "50"
            - "-z"
            - "60s"
            - "http://svc-a-service:9000"
      restartPolicy: Never  
  backoffLimit: 4
