# Stage 1
FROM python:3.10 AS builder

# Create an app directory
WORKDIR /app

COPY requirements.txt .
# Install Dependencies
RUN pip install --no-cache-dir -r requirements.txt 

COPY app.py app.py

# Stage 2: Production
FROM python:3.10-slim
WORKDIR /app

# Copying the required dependencies
COPY --from=builder /usr/local /usr/local
COPY --from=builder /app /app

# Create a non root user
RUN useradd -m appuser
USER appuser

# Run the application
CMD ["python", "app.py"]
